### ISSUE TITLE
WSS 

### ISSUE THREAD

**Issue by volkovmqx** [Barbosik/MultiOgar#128]
HTTPS require WSS, any chance to implement this ?

**Comment by MastaCoder** [comment]
https to the server, are you implementing some sort of login system?

**Comment by volkovmqx** [comment]
when the client is loaded in https, an error is thrown , made by the browser : 
`SecurityError: The operation is insecure.`
this is saying that it should load wss instead of ws. and the game won't start.

**Comment by Influxx** [comment]
You would need to implement wss on your server and connect to it using wss://address:port, this is unrelated to MultiOgar.

**Comment by volkovmqx** [comment]
hell no.

**Comment by Barbosik** [comment]
yes, currently something strange with secure web socket connections.
Needs to investigate on how to handle secure connections with WebSocket properly.

**Comment by Barbosik** [comment]
in order to use WSS, there is need to provide server with private key and SSL certificate.
I will add support for WSS, but you will need to provide your own certificate and private key for the server.

**Comment by volkovmqx** [comment]
Awesome

**Comment by David1ali12** [comment]
Does any1 know how to connect to server with new protocol on agario client Before it  connect("ws://example:port") any idea what's it now

**Comment by Barbosik** [comment]
fixed. To support TLS connections, there is need to place private key and certificate into ./ssl/ folder.
You can generate it with openssl:
```
openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 100 -nodes
```

**Comment by volkovmqx** [comment]
even it said the TLS supported (i generated both files), i can't seem to make the wss work (i changed the ws to wss in the client.

**Comment by SimonOrJ** [comment]
I'm trying to find a client that supports https.  Are you able to provide the link to the client, please?

**Comment by volkovmqx** [comment]
client that support wss* , https is not a thing that the client will support or no. 
you can change the ws:// string to wss://

**Comment by Barbosik** [comment]
**volkovmqx**: can you show what error is shown in your client?

I'm tested it from my client, both ws and wss works good.
Also tested it with WireShark, with wss it really using TLS.

Currently test server bubble-wars.tk is shut down due to error in ws code.
Probably there is mistake in ws code and someone exploit it to shut down the server.
I'm working on collect information about it. After that I will start test server again.

**Comment by Barbosik** [comment]
**SimonOrJ**: Any client which works on https page will use WSS, because browser will not allow to use non secure websocket from secure page. Previously agar.io worked in both versions. But now it works in http mode only. May be they changed it after big update. I have no idea why. Because secure websocket connection is more stable, because proxies doesn't affect it's headers.

**Comment by Barbosik** [comment]
WSS connection to MultiOgar test server:
![Screenshot](http://i.imgur.com/1Ex0EzX.png)

**Comment by firattusta** [comment]
Hi
i am using windows server 2012 r2
I couldn't solve the logic
What do I need to do to have the incoming link wss: //
I set up the certificate, remote desktop connection but I couldn't

windows server 2012 r2
how should i make adjustments

I have been dealing with this for 1 week I couldn't understand the problem working logic

server file works like this
windows server 2012 r2 remote desktop
does not write wss: // as in the picture

![problem](https://user-images.githubusercontent.com/66503874/83934815-22566900-a7bc-11ea-929f-b744fd9b6663.png)


I would be very happy if you help me thanks

**Comment by CrosWebsite** [comment]
help me plz ?
