### ISSUE TITLE
To get better physics

### ISSUE THREAD

**Issue by inxlio** [Barbosik/MultiOgar#159]
the pshysics 
They are not as good as ogarUL , pls make better ... thx

example: popsplit not working 
the all times

**Comment by Megabyte918** [comment]
is this a joke

**Comment by inxlio** [comment]
in ogarUL the popsplit working all times , in multigar NOT WORKING THE ALL TIMES ...

**Comment by inxlio** [comment]
in ogarUL , you can configure all variables ( splitspeed , splitdistance , splitVersion , etc) 
pls add more features and to get better physics

**Comment by liomessip** [comment]
duplicate?

**Comment by David1ali12** [comment]
Use Ogarul then it lags with 0 players :smile:

**Comment by NatsuTheGreat** [comment]
^^^ Now stop making these useless issues. If MutliOgar popsplit sucks, go on OgarUL. PROBLEM SOLVED!

**Comment by darknight99x** [comment]
Somebody needs to code an agar.io alternative in a different language, javascript is just too laggy and not reliable.

**Comment by Barbosik** [comment]
@darknight99x: actually node.js works very fast. I even surprised.
There is just three things which I miss in node.js:
* Sometimes (very rarely) there is need to execute some actions in parallel. Unfortunately node.js doesn't provide such ability. 
* it's a crap when you need to flush some async operations in blocking mode. Because they enqueued into setTimeout or proces.nextTick but you're need to flush it just now, with no pending. For example Logger.shutdown. It's executed from process.exit handler. So all things enqueued into setTimeout and process.nextTick will be lost, but you need to flush it.
* weak type language leads to hidden bugs, and I cannot find good environment which scans the code and highlight problematic code

But node.js definitely works like charm :)
I'm looking for good environment for node.js. Does anyone can suggest something?
