### ISSUE TITLE
[Suggestion] skins in text file

### ISSUE THREAD

**Issue by NoiseControllers** [Barbosik/MultiOgar#166]
as in [https://github.com/AJS-development/Ogar-unlimited](url)

**Comment by Barbosik** [comment]
What is the reason to store skin names on the server?

**Comment by MastaCoder** [comment]
ew, Ogar-Unlimited features.

**Comment by NatsuTheGreat** [comment]
No, lets not do this...

**Comment by NoiseControllers** [comment]
the client they are illegal to add skin in server and not have to have a customer.
There would be a possibility this being added.

**Comment by MastaCoder** [comment]
?

**Comment by NatsuTheGreat** [comment]
Exactly.

**Comment by NoiseControllers** [comment]
Customers are illegal, I usually use agar.io and I would like to have other Skinnes.
What's wrong with that? I do not understand with people negative voting

**Comment by MastaCoder** [comment]
Google translate doesn't seem to be working.

**Comment by NatsuTheGreat** [comment]
I am dying of laughter HAHA

**Comment by SimonOrJ** [comment]
> Illegal customers

> Customers are illegal

 ... uhh.... huh?

The official Agar.io game does not accept custom skins.  It can only show official skins.  For example, if you want to use the shark skin, you can start your name with:
`<shark>`

If you do want custom skins, you can use Ogar-Unlimited.

**Comment by Barbosik** [comment]
Custom skins is vulnerable. It allows bad guys to deploy malware, spyware and virusware to other players computers. Each picture should be checked for malware and viruses before allow it to display for other players.

**Comment by Barbosik** [comment]
There is no need for skin list on the server side. Because server doesn't know which skin is supported by client and which is not. Skin is a client feature. Server just helps to share player skin name with other players. That's it.

You can use skin text file on the client side.
If you need to implement set skin command in your client (for example when the user selects some skin with the button). You can just send chat command `/skin %kraken` from your "Select Skin" button handler. And server will assign selected skin to the player.
