### ISSUE TITLE
packet optimization 

### ISSUE THREAD

**Issue by henopied** [Barbosik/MultiOgar#172]
I think that we can increase the performance of multiogar immensely if we were to not have the packets be classes but rather have them be in an object that can be reused and to no longer use the buffer writer and buffer reader classes. Example `new Packet.UpdateNodes(this, [], [], [], this.clientNodes)` could be changed to `Packet.BuildUpdateNodes(this, [], [], [], this.clientNodes)` and Packet would be an object with many functions and helper functions but it would only be created once.

**Comment by Barbosik** [comment]
I don't think you can optimize performance in such way. And even mode performance it may decrease performance.
It's due to specific of memory management in languages with GC.
JIT compiller is smart enough to reuse memory for small object which is allocated and released for short time. So, actually it already works in suggested way. 

But if you will hold object for a long time it will prevent GC to manage memory fast and efficiently. It will leads to memory leaks and longer time for memory allocation.

So, it's better for performance to create a lot of small objects for a short period of time, than allocate one big object and keep it forever.

**Comment by Barbosik** [comment]
you can run the server with profiling and see how much time is used for memory allocation.

new Packet.UpdateNodes takes for about 0.01 % of execution time.
Cell lookup and resolve collision takes for about 75% of execution time.
Cell sort takes for about 5 % of execution time.
WebSocket.send takes for about 20% of excecution time (inside WebSocket code).

So, there is nothing to optimize. new Packet very fast, and I don't think that you can make it faster.
