### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by TheGoldenXY** [Barbosik/MultiOgar#177]
For some reason, the MultiOgar emulator crashed on one of my servers. I am using the latest version.

After days of uptime, the server suddently crashed.

http://prntscr.com/bs1qq7

**Comment by ItzLevvie** [comment]
"I am using the latest version." - @TheGoldenXY

By looking at your screenshot, I can tell that you're currently running MultiOgar 1.2.34, upgrade to MultiOgar 1.2.38 as that is the latest update as of 12/07/16.

**Comment by MastaCoder** [comment]
Genius catch up there ^^

**Comment by Barbosik** [comment]
could you show the latest messages from log file?
It's hard to say why it killed, because your environment doesn't show any message with reason to kill the server.
At a glance it's because out of memory. You're running server on machine with small amount of memory. And you're using a lot of bots. Each bot and each player eats some amount of memory. So, your server configuration doesn't fit with hardware resources.
