### ISSUE TITLE
Movement physics issue

### ISSUE THREAD

**Issue by Chancerst** [Barbosik/MultiOgar#18]
This is your Private Server Pack.
![default](https://cloud.githubusercontent.com/assets/19770308/15883666/4b9a906c-2d85-11e6-9bf9-e0aaf9ce667f.png)

And this is Real agar.io.
![1](https://cloud.githubusercontent.com/assets/19770308/15883670/58d2adaa-2d85-11e6-931f-439b04a3f21d.png)

Private Server looks like close cell and cell.
But real agar.io looks like regular cell and cell.

But you think, it's not bug, you don't have to fix this.

Thank you for make agar.io private server!

(i'm korean, so i can't use English well.)

**Comment by Barbosik** [comment]
I know about it and I want to fix it.

**Comment by Barbosik** [comment]
I rewritten collision physics, so this issue is resolved. 
With one note. MultiOgar uses single pass collision resolver, so if some cell is under pressure from several other cells, the cell which is under pressure may be clamped and you will see very similar behavior.

I'm not so familiar with physics engines, so I don't know how to fix it with single-pass collision resolving.
On the other hand, multi-pass collision resolving will be too slow.
