### ISSUE TITLE
I cant eat mass

### ISSUE THREAD

**Issue by liomessip** [Barbosik/MultiOgar#188]
Hello , i cant eat points when I'm smaller than the points

**Comment by Megabyte918** [comment]
you have to be bigger than the points to eat the points.

**Comment by Megabyte918** [comment]
you have to be bigger than the points to eat the points.

**Comment by NatsuTheGreat** [comment]
What kind of question was that?! Have you forgotten logic, liomessip?

**Comment by liomessip** [comment]
i have big servers , the mass +40 and players with 10 mass cant eat the mass please help me

**Comment by darknight99x** [comment]
@NatsuTheGreat I noticed this in HungerGames, which breaks the gamemode.

**Comment by MastaCoder** [comment]
@darknight99x not really, I like the fact that they have to eat the smaller piece to get to the bigger ones.

**Comment by Barbosik** [comment]
don't set food size > 20, because it will leads to client bugs. 
The cell with size <= 20 treated as food. 
The cell with size > 20 treated as player cell/virus/eject

**Comment by SimonOrJ** [comment]
I think the food eating function is server sided.  This does break the hunger game gameplay

**Comment by MastaCoder** [comment]
Food eating has to be server sided :package:

**Comment by SimonOrJ** [comment]
@Barbosik, you misinterpreted the issue.  It was a small cell cannot eat larger food cell.  For example, cell with size 1

**Comment by Barbosik** [comment]
The problem is not with server. But with the clients. 
Player cell with size < 32 can leads to bugs and low performance on the client side. 
Food cell with size > 20 will leads to bugs and graphics artefacts on the client side.

It's because there is no way to notify client if some cell is food. 
The client detects if the cell is food just with check if it's size < 20.

So, if you will use food with size larger than 20, the client will render it as player cell.
The same thing with player cell, if it's size is less than 32, the client will render it as a food cell.
It will leads to graphics artefacts.
Also it will leads to the bugs with statistic calculations on the client.

**Comment by Barbosik** [comment]
The food cell is intended to be small. it allows client to render a lot of food cells with simplified renderer.
But if you're using a lot of large food cells. It will leads to performance issues on the client side.
