### ISSUE TITLE
Spectate mode is broken in my client

### ISSUE THREAD

**Issue by lulzyyy** [Barbosik/MultiOgar#196]
examples. it was fine previously, what did you change?
http://c0nsume.me/private4.php?ip=149.56.131.181:24270
http://c0nsume.me/private4.php?ip=146.185.167.9:443
http://c0nsume.me/private4.php?ip=146.185.167.9:444
 it's weird, but there it's working fine
http://c0nsume.me/private4.php?ip=149.202.87.51:443

**Comment by Barbosik** [comment]
I just enabled `serverScrambleLevel = 2` to reduce bots. Some clients reset camera position on border update it's the reason why they have broken spectate mode. You can fix it by remove code which reset camera position and camera scale on border update.

**Comment by inxlio** [comment]
@lulzyyy  you can help me for use skins without [skinName]

**Comment by liomessip** [comment]
@lulzyyy  You can help me for use skins without skins name in the nick

**Comment by lulzyyy** [comment]
fixed

**Comment by Barbosik** [comment]
@lulzyyy: I've found that your client spamming server with invalid messages (20, 111, 112). I recommend to remove these messages from the client. You can send custom commands through chat commands.

There are bad guys which attempting to spam the servers with random bytes, and I will add protection from this. It may also affect your client, because these invalid messages will be detected as spam

**Comment by lulzyyy** [comment]
it should be fixed now. these messages are from my custom servers (20 - w release, 111 - send skin, 112 - send password)
