### ISSUE TITLE
I think there's an issue with virus explosions.

### ISSUE THREAD

**Issue by NatsuTheGreat** [Barbosik/MultiOgar#220]
It seems like the falls into an infinite loop. I played instant merge, 60 bots, 2 players 32 max cells and the server just freezes. The console doesn't respond either, so it's definitely something like ```Max call stack size exceeded``` only it doesn't give out errors in the console.

**Comment by Barbosik** [comment]
did you used server code with uws instead of ws module?

**Comment by NatsuTheGreat** [comment]
uws.

**Comment by Barbosik** [comment]
Probably it's uws issue. Because I didn't catch such behavior for a long time run on ws.
Virus explsion leads to send a much larger packets to the client. May be there is some issue with memory management in uws

**Comment by NatsuTheGreat** [comment]
What do they really have to send? I see a lot of calculations and an array in virus.js doesn't seem like much.

**Comment by NatsuTheGreat** [comment]
I think I fixed it, pretty sure it was a problem in updateMoveEngine. There was the ```// Move moving cells``` for loop causing the problem. I kind of re-did the collision engine. It saved a lot of performance for ejected mass and in case of large amounts of player cells. It fixed bugs too.  :)

**Comment by Barbosik** [comment]
so, it was dead loop in your mod?

**Comment by NatsuTheGreat** [comment]
Sorry, I had to go bed last night. But apparently the for loop some how got stuck and became an infinite loop. I fixed it by removing ```else i++;``` and moving ```i++``` to the third part of the loop.

**Comment by NatsuTheGreat** [comment]
@Barbosik What does this do?

```
        if (minCell.getAge(tick) < 15 || maxCell.getAge(tick) < 15) {
            // just splited => ignore
            return;
        }
```
It prevents eating collision for cells under the age of 15 ticks?

**Comment by Barbosik** [comment]
@NatsuTheGreat: I fixed it by removing else i++; and moving i++ to the third part of the loop.

it's incorrect and will leads to bugs. 
The correct way is to use `else i++` instead of moving 'i++' into third part of `for` loop.

These 'for' loops removing items from collection. So, when 'if' condition is true and the item was removed from collection, the next item in the collection will be at the same index. To process it on the next iteration you need to skip 'i++'. If you will move 'i++' into 'for' declaration, then you need to add 'i--' in the `for' loop body.

**Comment by Barbosik** [comment]
@NatsuTheGreat: _What does this do?_

it checks if cell is just splitted, if so, it ignores collision for such cell.

**Comment by NatsuTheGreat** [comment]
>The correct way is to use else i++ instead of moving 'i++' into third part of for loop.

Well everything seems to be the same way on my server, and it fixed the freezing.

>it checks if cell is just splitted, if so, it ignores collision for such cell.

It ignored eating collision as I see. Should ignore eating collision.

**Comment by Barbosik** [comment]
@NatsuTheGreat: _Well everything seems to be the same way on my server, and it fixed the freezing._

it seems that you modified something in the code in wrong way. Because in original code it's just impossible to freeze at this code.

@NatsuTheGreat: _It ignored eating collision as I see. Should ignore eating collision._

exactly, it prevent eating for cell if it just split. 15 ticks = 0,375 seconds. It's the time which is used on vanilla server to disable collisions after split.

**Comment by NatsuTheGreat** [comment]
>it seems that you modified something in the code in wrong way. Because in original code it's just impossible to freeze at this code.

I actually didn't touch that loop, but it's doesn't matter anymore, everything works the way it did before :P

>exactly, it prevents eating for cell if its just split. 15 ticks = 0,375 seconds. It's the time which is used on vanilla server to disable collisions after split.

What the point of this though?

**Comment by Barbosik** [comment]
@NatsuTheGreat: I think the point is to reduce rigid body resolutions when a lot of cells intersects each other. This behavior is key point to make split in the same way as it works on vanilla.

**Comment by NatsuTheGreat** [comment]
Well, that statement is in the function to resolve NON-Rigid Body Collisions.

**Comment by Barbosik** [comment]
yes, it's important for instant merge mode. You will not be able to split without this check. Because your cell will be remerged just after your split. It will happens so fast, so you even didn't notice that you split and remerged again

**Comment by NatsuTheGreat** [comment]
Oh! Thank you.
