### ISSUE TITLE
:(  They manage to put bots on my server :(

### ISSUE THREAD

**Issue by multa2** [Barbosik/MultiOgar#247]
not like, but there are many bots in agario.city FFA 1 anti bot please :(

It can even handle bots

IS 

http://agar-api.tk/ Agar API (or Agar.io API) : best bots for MultiOgar and Ogar servers!

when the hack is public, everyone will have bots

![image](https://cloud.githubusercontent.com/assets/20700185/17292092/b1bfb3b8-57b5-11e6-987b-eb8d7e780c54.png)

![image](https://cloud.githubusercontent.com/assets/20700185/17292182/398a15a4-57b6-11e6-82e8-70c2d3b5733e.png)

**Comment by ItzLevvie** [comment]
As far as I know, the Developers of AgarAPI are @nulcearc and @David1ali12.

According to the comment they made below.

![image](https://cloud.githubusercontent.com/assets/11600822/17295596/ce4e186e-57f4-11e6-8aa6-9173038f658b.png)

^^ Unknown said, that they won't release the client now as private servers cannot handle more than 55 bots and therefore private servers aren't powerful as of yet.

This means that when they release the client, they will remove private servers support, so that people cannot bot on private servers.

**Comment by CalvinDKHD** [comment]
Uhmm, i mean i want it for my server.... Just for admin use.

**Comment by CalvinDKHD** [comment]
my skype : calvin.leonhardt
