### ISSUE TITLE
I have two questions.

### ISSUE THREAD

**Issue by NatsuTheGreat** [Barbosik/MultiOgar#271]
@Barbosik 

1. What is the cause of linesplit failure?
2. When do I need to use updateNodeQuad(node)?

**Comment by MastaCoder** [comment]
1. Rigid bodies of cells or something, don't remember about it much :smile:

**Comment by NatsuTheGreat** [comment]
Well that I know. :/ But what could be the problem in it? Seems like a good function.

**Comment by Barbosik** [comment]
root of cause for linesplit issue is rigid body physics. The cells should not penetrate each other when moving. Currently cell movement implemented with direct cell coordinate update, it doesn't allow to resolve rigid body collisions in such way, so they will not penetrate each other.

**Comment by NatsuTheGreat** [comment]
@Barbosik Thanks you for your answers.

1. I am still a little confused on it. Could you explain it more, please?

2. Thank you!

**Comment by Barbosik** [comment]
@NatsuTheGreat:

1) in order to process rigid body collisions, there is need to calculate movement vector instead of modification of cell coordinates directly. Without it, you cannot handle rigid body collisions in the way which prevents cell overlapping on cell move. If cells can overlap each other, they will affect movement direction of each other, because extrusion force should be applied to both overlapped cells. It add small movements in random direction and your cells line will just spreading into cells heap

**Comment by NatsuTheGreat** [comment]
So the problem is extrusion force?

**Comment by NatsuTheGreat** [comment]
http://prntscr.com/c2wqg6

**Comment by NatsuTheGreat** [comment]
I had to be very delicate.

**Comment by Barbosik** [comment]
the problem is that cells can overlap each other on cell movement. When it happens, we need to resolve it, and it's done with extrusion force, but it add random fluctuations in movement direction.

**Comment by NatsuTheGreat** [comment]
I made a small fix, but.. For some reason, sometimes the cells don't split Math,PI/2 and linesplit doesn't work.

**Comment by Barbosik** [comment]
if the cells overlap each other before movement - it's ok and will works fine with extrusion force.
But if they didn't overlapped before movement and overlapped after movement - it's the issue and it will leads to problem with linesplit. To fix it, there is need to add check which will prevent movement to coordinate which is occupied with another cell. But you cannot implement it when the cell coordinate is changed directly. 
You need to calculate movement vector with no change cell coordinate. And then check if movement in that vector is safe (doesn't overlap other cell). If it's not safe, you need to fix movement vector, but not coordinate.

**Comment by NatsuTheGreat** [comment]
Why does it add random angles though?

**Comment by Barbosik** [comment]
because when cell B is pop-out from cell A, it can overlap cell C. And if it will happens, both cells (B and C) will get extrusion force. But at the same time the cell B has extrusion force from cell A (from which it pop-out). So cell B will ping-pong from cell A to cell C and it will add extrusion force to both - cell A and cell C. This force has some small calculation error due to limited float type resolution. It's small, but it will be applied a lot of times, because of ping-pong in a loop. And in sum it will leads to random shift. And cells A, B and C will fly away from each other in random direction.

**Comment by NatsuTheGreat** [comment]
I understand. I have multiple fixes, but they all cause problems. Linesplit works though.

**Comment by NatsuTheGreat** [comment]
Look what I was even able to do. http://prntscr.com/c2x1j1

**Comment by NatsuTheGreat** [comment]
Hey, Barbosik, is extrusion force the reason why the doublesplit are like agar.io?

**Comment by Barbosik** [comment]
extrusion force is just body physics

**Comment by NatsuTheGreat** [comment]
Thank you for your help Barbosik, I appreciate it.
