### ISSUE TITLE
Grow with Virus

### ISSUE THREAD

**Issue by MertOtrk** [Barbosik/MultiOgar#29]
1: We dont grow with virus.
Because last cell eat virus. -  Dont like to Ogar
2: Split speed ( Space or Press W, - too slowly splitting. ). -  Dont like to Ogar
3: Explode ( with virus ) - i think so, angle problem. Explode, Dont like to Ogar

Can you fix them ?

**Comment by Barbosik** [comment]
1. Can you explain please, what exactly did you mean? I just tested it, if I eat virus, the mass grows up...

2. It's in progress, I changed split and eject physics, to be more close to vanilla. But split speed still should be tuned.

3. Explode with virus is the same as in ogar, I didn't changed angle. The only thing that was changed is eject movement (speed). Can you please explain what exatly "angle problem"?

Some note, if you playing Experimental, it has some bugs, because currently the code for Experimental game mode is broken.

**Comment by Barbosik** [comment]
2 and 3 fixed.

Can you explain please 1. What means "We dont grow with virus"?
It seems that all works ok, if you eat virus it add virus mass to the player.
So, what's wrong?
