### ISSUE TITLE
High CPU.

### ISSUE THREAD

**Issue by NatsuTheGreat** [Barbosik/MultiOgar#36]
So today I was playing on a fresh version and RIGHT when it starts I check my CPU it's 85+. I end the task, CPU drops down to 12. Is it something wrong with the game or my computer?

**Comment by Barbosik** [comment]
cannot reproduce

**Comment by MertOtrk** [comment]
Same problem :(

**Comment by Barbosik** [comment]
if you have problem post it's detail (your hardware, player count, bot count, etc).

When you posting issue that "something somewhere under some conditions is going somehow wrong".
It doesn't help, because I have no idea what is wrong, with what conditions, why it's wrong.

**Comment by NatsuTheGreat** [comment]
I have two players on.

**Comment by Barbosik** [comment]
it's ok if you're using slow computer

**Comment by NatsuTheGreat** [comment]
It's a toshiba. I don't think [this](http://prntscr.com/bfnbe7) is slow.

**Comment by MertOtrk** [comment]
My server:
128 GB of RAM (DDR3 ECC 1600 MHz)
2 x480GB SSD  SOFT
Intel  E5-1650v2 (3,5 / 3,9 GHz)
- $179.00/month -

-----

Bu sorun genel olarak "leaderboard packet" ile alakalı. Ben bu paketi güncelleyerek, performans kaybının önüne geçtim. Ancak bu client tarafı için geçerli oldu, server tarafı çok fazla cpu kullanmakta. Bunun nedeni; (bence) updatenodes packetinin yüklü veri göndermesi. Bu zaman aşımına uğratıyor.

----

This problem probably "leaderboard packet" with relevant ( i think so, because this packet repeat at every 1 second ). I am update this package, we prevent the loss of performance. But, this was valid (true) for client-side, server-side using too much CPU. İ think, we will update updatenodes.js. Because this packet is using high cpu.

**Comment by NatsuTheGreat** [comment]
I can 20+ different tabs (youtube, etc) and the CPU is staying at 12 and under. And then when I have that tab open (my server) boom, the CPU is 80+.

**Comment by Barbosik** [comment]
**MertOtrk**: I don't think that leaderboard packet consumes a lot of cpu time. It's called once per second.
About updatenodes, yes, it's the bottle neck. But I have some ideas, so I will implement it soon. It should reduce cpu load.

**Comment by Barbosik** [comment]
**NatsuTheGreat**: it's a client problem, not the server. You can look for server cpu consumption in the task manager. Just look for process with name "node".

**Comment by NatsuTheGreat** [comment]
Nodejs serverside is running fine with 1.2 CPU

**Comment by NatsuTheGreat** [comment]
but the thing is this has never been so before. It's always below 40 CPU. It just exceeded 95...

**Comment by NatsuTheGreat** [comment]
Just discovered something completely weird... When I am on other tabs, the CPU is 12- but when I go on that tab, the CPU rises back 90+. And again when I switch to a different tab, the CPU drops. And the server hasn't even been started yet.

**Comment by Barbosik** [comment]
**NatsuTheGreat**: you're talking about the client. Ask moneyclip to fix it.
It's not related to the server.

From server side, you can just decrease cpu load with modifications in gameserver.ini.
Change it to avoid large amount of cells on the screen (decrease food amount and bot amount).

**Comment by NatsuTheGreat** [comment]
It's not the client. I was playing solo on original agar.io while checking CPU, 50-. Now when I play on my server, boom, cpu 80+

**Comment by Barbosik** [comment]
**NatsuTheGreat**: it's ok, because when you playing on your private server, your computer needs to execute agario client and server simultaneously. So, 50-60% of your cpu is consumed with agario client and 20-30% of your cpu is consumed by private server. In sum its 60+20 = 80%.
You can decrease cpu load with modifying gameserver.ini. Just use not so much food and bots.

**Comment by Barbosik** [comment]
NatsuTheGreat: check the latest version. I implemented new physics engine, which works much faster.
Now I can run up to 500 bots :) 
It improves performance dramatically
