### ISSUE TITLE
Players always starts at 9 mass

### ISSUE THREAD

**Issue by ItzLevvie** [Barbosik/MultiOgar#58]
MultiOgar: **(starts at 9 mass when spawned)**

![image](https://cloud.githubusercontent.com/assets/11600822/16209474/1bd0f2e6-372f-11e6-942d-f3a336485a38.png)

Vanilla agar.io: **(starts at 10 mass when spawned)**

![image](https://cloud.githubusercontent.com/assets/11600822/16209507/4a541e40-372f-11e6-9072-fff6b979bf20.png)

**Comment by Barbosik** [comment]
it's not a bug. Vanilla uses mass = 10.24.

Actually the server works with size, not with mass. But I leave config values in mass units.
The server sends cell size as integer value, so there is a rounding.
If you set mass = 10.00 it will be recalculated into size = SQRT(mass*100) = 31,6228.
It will be send to client as integer size = 31. The server still store it as 31,6228, but there is no way to notify the client about size value with floating point. So, the client will show it as mass = 31 * 31 / 100 = 9,61. The client also round it before displaying to just 9. But the real mass is 10.

So, you need to specify mass 10.24 instead of 10, to get mass 10 on the client side.

**Comment by NatsuTheGreat** [comment]
^^ The rounding problem is why ejected mass cells go from 14 when being shot, and to 13 when stopped in agar.io.
