### ISSUE TITLE
Merging Player Cells leads to an Increase in Overall Mass

### ISSUE THREAD

**Issue by SimonOrJ** [Barbosik/MultiOgar#59]
It may not be noticeable in vanilla gameplay, but this is definitely noticeable in the instant merging server.

**Comment by Barbosik** [comment]
Actually you can overload onEat function and define merge mass calculation with no correction.
This correction is important for viruses. May be it will be better just to change mass calculation for PlayerCell to not use correction. Need to compare with vanilla

**Comment by Barbosik** [comment]
SimonOrJ: I added anti-minion protection, so you can enable it with setting serverScrambleCoords = 1.
Unfortunately some clients, such as OgarUL with old protocol doesn't support it, so these clients will show jumping cells. But it works fine with vanilla client and ogar.mivabe.nl

**Comment by Barbosik** [comment]
I reworked mass calculations. Now server works with size instead of mass. It reduces SQRT calls for mass -> size conversions. So, it should improve performance for split and eject.

Also I removed mass correction for non-virus cell. Now mass always constant. If you split and remerge, your mass will be unchanged.

Please note that there is major changes in gameserver.ini, now there is size units instead of mass. Also some unused and redundand variables were removed.
