### ISSUE TITLE
New gameserver.ini Configuration is Complicated

### ISSUE THREAD

**Issue by SimonOrJ** [Barbosik/MultiOgar#74]
I know you are  trying to cut down on clock cycle for each game tick, but the new configuration options get too confusing when you have to use math yourself all the time.  We all are used to configuring by the mass size, not by the size of the cell.

Will it be okay if I came up with mass-to-size conversion system and make a pull request?  I believe the best thing to do is to let people input mass amounts and make the configuration loader parse the mass into the size.

**Comment by David1ali12** [comment]
It took me 10 mins  to figure out not every1 is good in math

**Comment by Barbosik** [comment]
actually configuration with mass will be more confuse. Because the value that you will set with mass will  not be the same as on the client display. Because it will be rounded in size. So, if you will use mass for configuration, it will be extremely complicated to setup exact mass. Because you will need to calculate size anyway, in order to find if chosen mass has integer size with no decimal fraction.

So, size is better. Because you don't need to search value by using brute force with mass->size->mass calculation on each step.

**Comment by SimonOrJ** [comment]
People who are coming from other Ogar server projects will be more used to inputting mass.  Many people wouldn't care if the display mass is not exactly the same as the server-side mass if the mass values are close enough.

This is what I meant by "input mass amounts and make the configuration loader parse the mass into size":
https://github.com/SimonOrJ/Ogar/commit/bea4d2414dfb9461421bf2adf7bee8f72c55bef2

**Comment by Barbosik** [comment]
I tried to use mass in the config, but it leads to a lot of confusion. For example it's not obvious for user why mass should be 10,65 instead of 10. There is need to maintain size/mass cache in the code for every mass value in the config and it's not so clean when and how to synchronize it correctly. So I just replaced it with size, it's more clean.

Another example - how to process the case when config contains two records:
```
playerStartSize = 64
playerStartMass = 100
```

what value should be used? It's a hell when config has two values for single variable.

**Comment by SimonOrJ** [comment]
There can always be a comment that says to use only one of the two possible configuration options.

**Comment by Barbosik** [comment]
but comment will not help to avoid random mistake. It will confuse user if he change some value, but it will be taken from another place. Such cases should raise error to get user's attention "something is going wrong". It's impossible with two names for single variable...

**Comment by Barbosik** [comment]
There is better way. We can set mass in the following way:
```
playerStartSize = massToSize(43)
```
but it requires to add support for it for ini parser

**Comment by SimonOrJ** [comment]
This might do it: https://github.com/SimonOrJ/Ogar/commit/79beff91d8009ff0df773e12df1d4673d0f57cbd#diff-ee5616beb8aa0f352a3f697cf7c1d331R1243

**Comment by SimonOrJ** [comment]
That method looks better

**Comment by MastaCoder** [comment]
But this isn't very hard math, you just have to multiply and divide.. My 11 year old sister figured that out when I showed it to her. (not the squareroot part though.)

**Comment by Barbosik** [comment]
The problem with mass is that it confuse users. For example. Some time you can split with mass 35, but sometime you can't. It's because minimum size to split is 60. But the size is rounded 2 times - before send to the client and before display to the user. So if you set playerMinSplitMass = 35 it will works incorrectly

**Comment by Barbosik** [comment]
merged
