### ISSUE TITLE
Disconnecting bug

### ISSUE THREAD

**Issue by Prime55** [Barbosik/MultiOgar#88]
If leave a tab opened without being on it, after 3-5 minutes i get disconnected and connected again and sometimes i don't reconnect until i refresh the page. I use chrome and the normal agario client. @Barbosik

**Comment by Barbosik** [comment]
Can you show disconnection message from the log file?
You can find the log file in the folder logs/MultiOgar.log

Probably it happens because server disconnects inactive users. You can disable it with setting serverTimeout = 0

But there is need to read log message to be sure.

**Comment by Barbosik** [comment]
For example, if your log contains records like this:
```
[NONE ][20-03-03] CONNECTED 127.0.0.1:52578, origin: "http://agar.io"
[NONE ][20-03-40] DISCONNECTED 127.0.0.1:52578, code: 1000, reason: "Connection timeout", name: ""
```

it's because serverTimeout set to 30. When you close tab with game in the browser, it stops to respond to the server. So server think that it's disconnected player and kicks him after 30 seconds.
You can disable it with serverTimeout = 0, or just increase timeout interval.

**Comment by Prime55** [comment]
@Barbosik Yes, this is what was happening. Setting serverTimeout to 0 worked. Thanks for helping. And yes...30 seconds, not 3-5 minutes lol.

**Comment by Barbosik** [comment]
I changed default value to 5 minutes
